### PR TITLE
ISPRK-29 Update to Spark 2.0.0

### PR DESCRIPTION
**Pull request by ghost**
https://issues.jboss.org/browse/ISPRK-29

### CODE REVIEW

**Comment by ghost** [comment]
@vjuranek @galderz Would you like to take a look before integrating?

**Comment by vjuranek** [comment]
@gustavonalle I'll run couple of tests later today

**Comment by vjuranek** [comment]
LGTM and tests are passing in various environments.

**Comment by ghost** [comment]
@vjuranek thanks a lot!
@galderz anything from you?

**Comment by galderz** [comment]
Integrated, thx @gustavonalle

**Pull request closed without merging**
