### PR TITLE
ISPRK-32 Enable junit style test reporting

### PR DESCRIPTION
**Pull request by ghost**
https://issues.jboss.org/browse/ISPRK-32

### CODE REVIEW

**Comment by alanfx** [comment]
@gustavonalle with this change, I am able to get JUnit results with test names in the `target/test-reports/junit` directory. However, the JUnit results files with the names are still written to the `target/test-reports` directory. According to https://github.com/etorreborre/specs2/issues/305, you can disable the JUnit sbt plugin with this:

```
val myProject = project in file(".") disablePlugins (plugins.JUnitXmlReportPlugin)
```

**Comment by vjuranek** [comment]
@alanfx yes, disabling `plugins.JUnitXmlReportPlugin` suppresses output in `target/test-reports`, but it this needed?

**Comment by ghost** [comment]
Disabled `JUnitXmlReportPlugin` and fixed the paths where reports are generated in order to respect the cross version compiling. 

Reports are currently generated in `target/scala-2.10/test-reports` and `target/scala-2.11/test-reports`

**Comment by alanfx** [comment]
@gustavonalle this change looks good to me. The bogus JUnit results are no longer generated, and the results that are generated look good. @vjuranek what do you think?

**Comment by vjuranek** [comment]
LGTM

**Comment by ghost** [comment]
integrated

**Pull request merged**
