### PR TITLE
ISPRK-20 Update to Infinispan 8.2.1.Final

### PR DESCRIPTION
**Pull request by ghost**
https://issues.jboss.org/browse/ISPRK-20

### CODE REVIEW

**Comment by galderz** [comment]
Testing...

**Comment by galderz** [comment]
Timeout:

```
[info] Exception encountered when attempting to run a suite with class name: org.infinispan.spark.ClusteredSuites *** ABORTED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:153)
[info]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[info]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.ready(package.scala:169)
[info]   at org.infinispan.spark.test.Cluster.startAndWait(InfinispanServer.scala:63)
[info]   at org.infinispan.spark.test.Cluster$.start(InfinispanServer.scala:357)
[info]   at org.infinispan.spark.ClusteredSuites.beforeAll(ClusteredSuites.scala:16)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   ...
[info] Run completed in 1 minute, 30 seconds.
[info] Total number of tests run: 14
[info] Suites: completed 8, aborted 1
[info] Tests: succeeded 14, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error]     org.infinispan.spark.ClusteredSuites
[error] (core/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 125 s, completed 11-Mar-2016 17:01:44
```

**Comment by ghost** [comment]
@galderz the timeout should be fixed by https://github.com/infinispan/infinispan/pull/4116

**Comment by ghost** [comment]
@galderz the timeout should be fixed, I've updated the PR to update to 8.2.1

**Comment by ghost** [comment]
@galderz integrating since CI is happy, please open an issue if you experience any more timeouts!

**Pull request closed without merging**
