### PR TITLE
Remove references to JPA

### PR DESCRIPTION
**Pull request by VaclavDedik**
Because of: https://github.com/infinispan/infinispan/commit/b0d58e638fdc19a6048454c33c1d805227c492b0

Won't this brake compatibility with infinispan 8.2.x though? Maybe you have a better solution in mind, this is a commit I integrated to product for now though.

### CODE REVIEW

**Comment by anistor** [comment]
Oops! I forgot to give people advance notice of this API change.

**Comment by ghost** [comment]
@anistor What about deprecating it on 9.0?

**Comment by anistor** [comment]
BaseQuery is an implementation detail, not really an API.

**Comment by ghost** [comment]
@VaclavDedik in order to keep compatibility with 8.2.x we'll need to resort to the good old reflection in order to extract the query string

**Comment by anistor** [comment]
Oh, by all means no! I'll put back `getJPAQuery()` then (besides the newly added one). Just give me a bit of time.

**Comment by anistor** [comment]
I've created https://github.com/infinispan/infinispan/pull/4650 and https://github.com/infinispan/infinispan/pull/4651 to undo the initial damage.

**Comment by anistor** [comment]
Do we still need this?

**Pull request closed without merging**
